#54 integration with backend 1
Informatique-Dev/demos pull request #62
Opened 2023-01-03 19:29 UTC by fatmaalzharaa

2023-01-03 21:07 UTC, Tasneem-Gad requested changes

2023-01-03 21:07 UTC, Tasneem-Gad commented on candi-meter/candi-meter-ui/src/app/core/services/config.service.ts
> + //   this.httpClient = new HttpClient(this.httpBackend);
please don't push with comment

2023-01-03 21:07 UTC, Tasneem-Gad commented on candi-meter/candi-meter-ui/src/app/profit.ts
> +  id: number;
this interface part of our project?

2023-01-03 21:07 UTC, Tasneem-Gad commented on candi-meter/candi-meter-ui/src/app/repo.service.ts
> +import { HttpClient } from '@angular/common/http';
same

2023-01-03 21:07 UTC, Tasneem-Gad commented on candi-meter/candi-meter-ui/.vscode/settings.json
> +    "cSpell.words": [
are you need this file

2023-01-04 07:54 UTC, fatmaalzharaa commented on candi-meter/candi-meter-ui/src/app/core/services/config.service.ts
> + //   this.httpClient = new HttpClient(this.httpBackend);
ok ..
done

2023-01-04 07:56 UTC, fatmaalzharaa commented on candi-meter/candi-meter-ui/src/app/profit.ts
> +  id: number;
no ,
done

2023-01-04 07:56 UTC, fatmaalzharaa commented on candi-meter/candi-meter-ui/src/app/repo.service.ts
> +import { HttpClient } from '@angular/common/http';
done

2023-01-04 07:56 UTC, fatmaalzharaa commented on candi-meter/candi-meter-ui/.vscode/settings.json
> +    "cSpell.words": [
no 
done

2023-01-16 12:44 UTC, ZinabHashem commented
solve conflict please.

2023-01-16 23:54 UTC, ZinabHashem commented on candi-meter/candi-meter-ui/src/app/core/services/resource.service.ts
> +  et(id: string | number): Observable<T> {
fix function name

2023-01-16 23:54 UTC, ZinabHashem commented on candi-meter/candi-meter-ui/src/app/app.component.ts
> +import { Component, OnInit } from '@angular/core';
OnInit why add this without use

2023-01-22 11:40 UTC, ZinabHashem commented
solve conflicts

2023-01-23 11:52 UTC, merged