Edit-InstallmentPage
Informatique-Dev/demos pull request #72
Opened 2023-01-30 16:01 UTC by AsmaMohame

2023-02-19 09:49 UTC, AbdelrahmanMohyeldin commented on retail-managment-system/rms-ui/src/assets/i18n/ar.json
> +    "customerName":" اسم العميل",
you can use dash case like other names

2023-02-19 10:09 UTC, AsmaMohame commented on retail-managment-system/rms-ui/src/assets/i18n/ar.json
> +    "customerName":" اسم العميل",
done

2023-02-19 23:53 UTC, AbdelrahmanMohyeldin approved these changes

2023-02-20 22:57 UTC, ZinabHashem requested changes

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/edit-installment.component.html
> +
"edit-installment" or "pay-installment" better for component name?

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/edit-installment.component.scss
> +    display: none;
you used this also as bootstrap. which work?

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/edit-installment.component.scss
> +    width: 400px;
why used px not %

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/edit-installment.component.ts
> +  private _snackBar: MatSnackBar,
use camel case

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/edit-installment.component.ts
> + clickButton(){
use better name convention for function name

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/edit-installment.component.ts
> +      this.dialog.closeAll();
use a function that you already added for close
to achieve single responsibility

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/edit-installment.component.ts
> +      this.paymentDate = this.installForm.controls['paymentDate'].value ;
line 80 and 81 is duplicated in fetchData function why?

line 78 can add this in fetchData and delete from here 
to make data that will be fetch in same place

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/receipt/receipt.component.html
> +          <th scope="col">Name :</th>
use translation

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/installment.component copy.html
> +<div class="main">
what is this file?

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/receipt/receipt.component.ts
> +  print: boolean =false
are you need this property?

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/edit-installment/receipt/receipt.component.ts
> +  constructor(@Inject (MAT_DIALOG_DATA) public editData : Installment,  private dialog: MatDialog,) { }
are you use this injects ?

2023-02-20 22:57 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/installments/installment.component.ts
> +  setDate(install : Installment)
use better name convention(meaningful) for function name

2023-02-20 23:09 UTC, ZinabHashem commented
![image](https://user-images.githubusercontent.com/96727804/220211093-c9757d54-fd68-4da0-b9dd-bce54ac4a066.png)

2023-02-21 23:06 UTC, merged