#85 employee page
Informatique-Dev/demos pull request #89
Opened 2023-02-15 22:42 UTC by fatmaalzharaa

2023-02-20 09:47 UTC, fatmaalzharaa commented on retail-managment-system/rms-ui/src/app/pages/employee/employee/employee.component.html
> +          [pageSizeOptions]="[5, 10,20]"
done

2023-02-20 09:48 UTC, fatmaalzharaa commented on retail-managment-system/rms-ui/src/app/pages/employee/employee/employee.component.html
>        </div>
done

2023-02-20 10:02 UTC, AsmaMohame approved these changes

2023-02-20 13:11 UTC, AsmaMohame approved these changes

2023-02-20 14:51 UTC, ZinabHashem requested changes

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/package.json
> +    "ngx-pagination": "^6.0.3",
are you use this package?

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/core/models/response.ts
> +  data: [T];
[T] or T[]

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/core/models/response.ts
> +export interface response<T>{
name of interface must be pascal case

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/core/services/resource.service.ts
> +  findAll(page:number,size:number): Observable<response<T>>{
why add new function?
why didn't use getList()?

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/employee/employee/employee.component.ts
> +    private _snackBar: MatSnackBar,
use camel case

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/employee/employee/employee.component.ts
> +    this.employeesRepository.getList().subscribe((result) => {
why add new function to get pagination?
use same function getAllEmployee()

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/employee/employee/employee.component.ts
> +    this.employeesRepository.findAll(page, size).pipe(
you already have function that get employee why make another?
call function getAllEmployee()

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/pages/employee/employee/employee.component.html
> +          [dir]="'direction-pagination'|translate"
direction is same in ar and en so you can delete this

2023-02-20 14:51 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/assets/i18n/ar.json
> +    "employee": "موظف",
add section for employee don't use costumers 

as structure we make in translation

2023-02-20 14:54 UTC, fatmaalzharaa commented on retail-managment-system/rms-ui/package.json
> +    "ngx-pagination": "^6.0.3",
yes

2023-02-20 14:55 UTC, ZinabHashem commented
- add card for employee in home page.
- use total row com from back in request to show this number in pagination after add or delete.

2023-02-20 15:10 UTC, ZinabHashem commented on retail-managment-system/rms-ui/package.json
> +    "ngx-pagination": "^6.0.3",
where?

2023-02-20 23:41 UTC, ZinabHashem commented
@AsmaMohame review again plz

2023-02-21 22:36 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/assets/i18n/ar.json
> +  "Employee": {
why start with capital character? 
use same case we use here

2023-02-21 22:36 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/shared/material-module/material-module.module.ts
> +import { NgxPaginationModule } from 'ngx-pagination';
NgxPaginationModule  is exist in project?

2023-02-21 22:36 UTC, ZinabHashem commented on retail-managment-system/rms-ui/src/app/core/layout/side-bar/side-bar.component.html
> -  </p>
why delete this ?

2023-02-27 20:04 UTC, closed without merging